# Generated by Django 4.1.5 on 2023-01-11 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
